# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18.x'

    - name: Set up database
      run: docker run -d --name mysql -p 3306:3306 dmytromolchanov/custom-mysql

    - name: Build back-end
      run: |
       go build -v ./...

    - name: Test
      run: |
       go test -v ./...

    - name: Create image
      run: |
       docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/mysql-fiber-go
       echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
       docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql-fiber-go